# Build a deb artifact on commit

name: Build deb on commit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get commit hash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build .deb
      uses: jiro4989/build-deb-action@v2
      with:
        package: nekofetch
        package_root: debpkg
        maintainer: propr and bbaovanc
        version: 0.2
        arch: 'amd64'
        desc: 'neofetch with nekos'
    - name: Upload deb as artifact
      uses: actions/upload-artifact@v2
      with:
        name: deb
        path: nekofetch*.deb
